name: Main

on:
  push:
    branches: [ main, release/*]
  pull_request:

jobs:
  Build:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

    strategy:
      fail-fast: false
      matrix:
        name: ["iOS", "tvOS"]
        include:
            - name: "iOS"
              scheme: "Container iOS"
              destination: "platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro"
              test: true

            - name: "tvOS"
              scheme: "Container tvOS"
              destination: "platform=tvOS Simulator,OS=15.2,name=Apple TV 4K (2nd generation)"
              test: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test
      run: >
        if [[ ${{ matrix.test }} == true ]]; then
          xcodebuild test \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES || exit 1
        else
          xcodebuild \
            -scheme "${{ matrix.scheme }}" \
            -destination "${{ matrix.destination }}" \
            ONLY_ACTIVE_ARCH=NO || exit 1
        fi

  Lint:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
      cocoapods: true
      spm: true

    steps:
    - name: Lint
      run: >
        if [[ ${{ env.cocoapods }} == true ]]; then
          pod lib lint
        fi

        if [[ ${{ env.spm }} == true ]]; then
          swift package description
        fi
